name: logstash-output-loki

on:
  push:
    paths:
      - images/logstash-output-loki/*
      - .github/workflows/logstash-output-loki.yml
  workflow_dispatch:

env:
  GHCR_IMAGE: ghcr.io/zebbra/logstash
  CONTAINER_PLATFORMS: "linux/amd64,linux/arm64"
  UPSTREAM_VERSION: 8.12.1-debian-11-r19
  TAG: 8.12.1-bitnami-loki

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: >
          docker buildx build --pull --push
          --build-arg VERSION=${{ env.UPSTREAM_VERSION }}
          -t ${{ env.GHCR_IMAGE }}:${{ env.TAG }}
          --platform ${{ env.CONTAINER_PLATFORMS }}
          .
        working-directory: images/logstash-output-loki
