name: postfix-relay

on:
  push:
    paths:
      - images/postfix-relay/*
      - .github/workflows/postfix-relay.yml
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'

env:
  GHCR_IMAGE: ghcr.io/zebbra/postfix-reley
  CONTAINER_PLATFORMS: "linux/amd64,linux/arm64"
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: >
          docker buildx build --pull --push
          --build-arg VERSION=${{ env.UPSTREAM_VERSION }}
          -t ${{ env.GHCR_IMAGE }}:${{ env.TAG }}
          --platform ${{ env.CONTAINER_PLATFORMS }}
          .
        working-directory: images/postfix-relay
